export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const UPDATE_FILTER_DATE = 'UPDATE_FILTER_DATE'

export const UPDATE_FILTER_SELECT = 'UPDATE_FILTER_SELECT'
